### ISSUE TITLE
Using Iter infused blocks to cross to the Nether causes a desync in SMP.

### ISSUE THREAD

**Issue by VoilaTada** [TheDrunkMafia/ThaumicInfusion#17]
I set up Iter infused blocks to go to and from the Nether but when a player other than myself used the block they would be stuck going back and forth until they signed out and back in. Additionally they appeared in a vanilla nether portal a short distance from the block instead of actually on the block but after their re-log they appear in the proper location.

**Comment by TheDrunkMafia** [comment]
Intresting, I'll have to debug that in my dev enviorment. I can safely say that, that should not be happening.

**Comment by TheDrunkMafia** [comment]
This has been fixed in Thaumic Infusion 4, do not use 3 as it is very unstable and buggy as you have found in with iter. Dont post and crashes/bugs with 3, as I am no longer supporting it. I may in the future implement the old block infusion in 4, but for now I am sticking with the simple foci until I am certain that the mod is stable.
