### ISSUE TITLE
Infusing Redstone Ore and updating the block creates Redstone Ore.

### ISSUE THREAD

**Issue by VoilaTada** [TheDrunkMafia/ThaumicInfusion#18]
Infusing Redstone Ore and updating the block replaces the infused block with the normal active Redstone Ore and drops the infused block. Then placing the infused block again allows a player to create infinite Redstone Ore and thus Redstone as a result.

**Comment by TheDrunkMafia** [comment]
Which version of the mod are you using?

**Comment by VoilaTada** [comment]
Looks like 3.966, according to the mods list in game.

**Comment by VoilaTada** [comment]
My discovery happened when infusing Redstone Ore with Messis and attempting to plant a crop on it.

**Comment by TheDrunkMafia** [comment]
That is the issue then, 3.966 is very old and unstable. Its infusion system of infusing aspects into blocks is obsolete now, as the new version works with a foci and infusing spaces. You can find the latest build here: http://www.curse.com/mc-mods/minecraft/220308-thaumic-infusion#t1:other-downloads Please be aware that 4 is not compatible with 3, due to a huge data structure change.

**Comment by VoilaTada** [comment]
I see. Thanks for clearing that up! :)

**Comment by TheDrunkMafia** [comment]
No problems. If you find any thing wrong in 4, then just post it here.
