### ISSUE TITLE
Aspect functionality is not clearly documented (TI 4.02)

### ISSUE THREAD

**Issue by Alaberti** [TheDrunkMafia/ThaumicInfusion#22]
I pulled every mod out except Thaumcraft 4.3.2.5, NEI, and Thaumic Infusion 4.02 and attempted to use the new system after watching your preview video (showing me that it should, in fact, work). Iter, cognitio, fabrico, and aer did not work (I suspect others don't as well) while lux and infernus do. There is no console log or crash, they simply do not work. I am running forge 1403, that may have something to do with it...help?

Edit: There are various typos in your documentation, do you have somewhere I could proof-read repost for you? 

Edit 2: Got iter to work, left clicking okay. There is a delay before the next teleport is allowed, is that allowed/documented?

Edit 3: Left clicks are the key, okay! However, cognitio does not disguise as a bookcase.

**Comment by TheDrunkMafia** [comment]
I am limited to what I can explain in the research page, which is why I am adding in a new block to analyse aspects and find out what they do that way. Iter does have a cooldown before teleporting again, this is to stop you from being caught in a teleport loop.

On terms of cognito, to debug I need the TI_Transformer.log that will be located in the root of your instance. It will tell me if the method required for cognitio to work had my code injected into it.

**Comment by Alaberti** [comment]
Done! http://pastebin.com/iiS2Y3Dg

**Comment by TheDrunkMafia** [comment]
The correct method has been injected with my code, I shall debug the effect when I get into my dev enviorment

**Comment by TheDrunkMafia** [comment]
Cognitio is working in my dev environment, the only issue is that vanilla is hard coded to recognise bookcases and spawn particles. Other than that, the enchant bonus is applied and works the same as a bookcase would.

**Comment by Alaberti** [comment]
So it works as a bookcase but is not disguised as one? Got it. Now that I know, I think we're solid here!
