### ISSUE TITLE
crash at startup after updating from 4.07 to 4.1

### ISSUE THREAD

**Issue by ate0ate** [TheDrunkMafia/ThaumicInfusion#31]
Using the latest forge (1490) I now get this crash at startup using thaumic infusion 4.1.
I don't actually see thaumic infusion mentioned, but it is the only mod I updated and reverting back to 4.07 solves the crash. I am also using fastcraft.

http://pastebin.com/PtsRfPqw

**Comment by BeardStroker** [comment]
Similar thing here, Happened after upgrading to 4.1 Posted this to Minecraft forums before remembering my github account so sorry for reporting twice :P 

http://pastebin.com/hjyaQNrB

**Comment by HyperMan19680** [comment]
I got a couple as well from this same problem. Such a shame, I was really looking interested in this update.

**Comment by TheDrunkMafia** [comment]
I believe I have just fixed this issue, I am releasing a hotfix for it now on curse. It should fix both of your issues, it was a minior oversight on how to do the injection of my code into the blocks. But it works now and better than before, since the code was just injecting it into any method it could find compatible in blocks, now its only doing it with actual block methods.

Heres an upload of the hotfix while I wait for curse to accept the new version: http://puu.sh/j0E4k/24ddb2ded2.jar

**Comment by BeardStroker** [comment]
http://pastebin.com/dmLrs8NY

Tried with the hotfix, now the client crashes before the Java window pops up :P

**Comment by TheDrunkMafia** [comment]
That crash is caused by invalid packets being sent and there is no room for TI to be causing such a crash, have you updated any other mods in your instance?

**Comment by BeardStroker** [comment]
Nope, it works fine with 4.07 but with 4.11 it crashes a few seconds after pressing play. I'll try removing some of my later additions just to rule them out but the same setup just started fine with 4.07

**Comment by TheDrunkMafia** [comment]
Interesting, I am not getting this crash in my testing pack.

**Comment by TheDrunkMafia** [comment]
You seem to be using:
thaumicinfusion{4.05} [Thaumic Infusion] (ThaumicInfusion-4.06.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available

**Comment by ate0ate** [comment]
Nope, there's definitely still an issue with the hotfix. Now I crash as soon as I hit startup. Only changes are thaumic infusion updating to 4.11 from 4.07. Reverting fixes the crash. Just for the heck of it I tried from the link you provided here as well as cursefoge. Here's the relevant portion of my fmlclient.log

http://pastebin.com/p0v79qCe

**Comment by BeardStroker** [comment]
ahhh I see the problem now, its not that I am using that old version, but the crash does not produce a crashlog, and I just assumed the latest one was caused by the hotfix. sorry about that, but the issue still remains. here is the console log, maybe that gives some relevant info.

http://pastebin.com/AsFYHX47

**Comment by TheDrunkMafia** [comment]
It's too late to look into this at the moment, I'll work on it early tomorrow and get it fixed. I know where the crash is originating from, however the solution is going to be hard due to the nature of the issue. ASM is a fun thing especially when mixed in with load of other mods making changes to the same class and also obfuscation. Sorry about this.

**Comment by ate0ate** [comment]
No need to apologize, 4.07 works perfectly well in the meantime. I love the mod and appreciate your time and effort looking into this. Thank you.

**Comment by BeardStroker** [comment]
Great! :) Will be looking forward to seeing the update, really appreciate your time. Loving the mod so far.

**Comment by TheDrunkMafia** [comment]
Right so after hours of building, testing and then rebuilding the mod. I do believe I've fixed the issue with the mod not launching while other mods exist in the instance. Would any of you be interested in testing this before I release it on curse, I've already ran it in a pack with 100 mods in it. But conditions that TI is working in will be different on each PC. If you are just download this version here: http://puu.sh/j1tOi/bf2e9be817.jar

If the mod happens to crash, please upload the TI_Transformer.log as well.

**Comment by ate0ate** [comment]
Thanks! Obviously I've only done minutes of testing, but I have no problems to report thus far. Everything starts up and loads appropriately by all appearances and worlds seem to generate just fine. The only thing worth mention ing so far is that upon loading an existing TI 4.07 world I get a notification from forge that thaumicinfusion:reg_infusedblocktutamen (or something very close to that) no longer exists. I would assume that this is perfectly normal?

**Comment by TheDrunkMafia** [comment]
Yeah, I've removed a few aspects which serve no purpose in the mod.

**Comment by ate0ate** [comment]
Okay. No problems at all then. I will report back if that changes, otherwise, thank you very much for such a unique mod!

**Comment by BeardStroker** [comment]
No problems so far here either, will continue testing tomorrow but so far everything works great.

**Comment by TheDrunkMafia** [comment]
Great, would any of you be able to upload the TI_Transformer file? I'd like to see if the injection is working correctly.

**Comment by BeardStroker** [comment]
No problem, here ya go. will try to playtest it some more just to see if something wonky happens.

http://pastebin.com/xwVWqBCv

**Comment by TheDrunkMafia** [comment]
Alright cool, so the transformer is working. I'll be rolling out a new update either today or tomorrow that will finish the changes being made to the block transformer and should make it work with every single block in the instance since some of them are being left out. Also the new update will come out with a new lang file and new effects.

**Comment by TheDrunkMafia** [comment]
New version is out, so for now this issue has been resolved. But I guess there would be other mods that wont like what TI does.
