### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Xiaminou** [TheDrunkMafia/ThaumicInfusion#33]
Forge: 1448
Thaumic Infusion: 4.16
Crash Report: http://pastebin.com/BzEmy2A9

Server crash on startup, client works fine.

**Comment by TheDrunkMafia** [comment]
Yeah, I know of this issue. Extra Utilities is calling block code before the world is launched, I'll release a hotfix soon.

**Comment by ate0ate** [comment]
I must give you credit, you sure are a quick fixer:)

**Comment by TheDrunkMafia** [comment]
Haha, that comes with this mod. Since I am trying to make my mod work with every other mod, mine will keep crashing until I find every glitch and bug with each mod ever made ;D So its going to be a long process, but hopefully the miore fixes I implement the less mods will have issues with mine.

In other news, Xiaminou. Can you try this version: http://puu.sh/jb8rH/ef26930038.jar I'd like to confirm that it is working before releasing the hotfix on curse.

**Comment by Xiaminou** [comment]
It's working!

**Comment by TheDrunkMafia** [comment]
Perfect, thanks.

**Comment by TheDrunkMafia** [comment]
Every incompatibility people find, the more I can make my mod work.

**Comment by Xiaminou** [comment]
well, my modpack has 251 mods, I update it daily so I do find a few incompatibilities every now and then, I like to think I contribute in my own way.
