### ISSUE TITLE
NEI Lists items as Infusion Stabilizers when they aren't / Ordo doesn't make items infusion stabilizers

### ISSUE THREAD

**Issue by Alaberti** [TheDrunkMafia/ThaumicInfusion#46]
This is a two-part issue on the same issue. I had a player report that cobblestone was being listed as an infusion stabilizer, which is crazy talk. He then investigated the issue. Below are his findings; he does a better job of explaining it than I.

https://www.dropbox.com/s/svmtwbba7ena1p8/Thaumic%20Infusion%20Test.pdf?dl=0

**Comment by TheDrunkMafia** [comment]
Yeah, Ordo should give blocks infused with it give of stability to Infusions. I traced the issue to my code only accepting base block methods & not interfaces which is what Thaumcraft uses to let blocks become a stabilizer, I will add an exception for it & upload it to curse. This has slip under my radar, because the code that is causing this issue is deep within my mod.

**Comment by TheDrunkMafia** [comment]
Updated the mod on curse, with a version that includes the fixes I've applied to ordo.

**Comment by Alaberti** [comment]
Awesome!
