### ISSUE TITLE
Some new and some old issues appeared again

### ISSUE THREAD

**Issue by LazerusKI** [TheDrunkMafia/ThaumicInfusion#48]
First of all: the effects wont vanish anymore ^-^

But at the same time, a few old problems appeared again.

Spiritus Infused blocks now have that "push" effect again, like flowing water. i think you fixed that a while ago.

Perditio is now persistent again, so when it explodes, the frame stays there. Also i noticed that you cant remove the infusion, since it counts as interaction - so the block blows up

**Comment by TheDrunkMafia** [comment]
Hmmm, I don't think spiritus will act like it use to any more since the way its currently being done, is the code is being ran ontop of the blocks own code. Which means I have allot of mobility when it comes to adding new functionality to the blocks, however actually editing the blocks properties is something that is now a thing of the past. So I might just have to remove spiritus or make it act like when ever someone gets close it vanishes.

Where perditio is concerned, my previous changes might have been overridden as I downloaded the 1.7.10 version from Github which was out of date, I will reapply the changes.
