### ISSUE TITLE
Transformer issue causing incompatibility with SpongeForge

### ISSUE THREAD

**Issue by simon816** [TheDrunkMafia/ThaumicInfusion#62]
There is an issue with Thaumic Infusion and SpongeForge. I have identified that TI is at fault.
(SpongeForge issue https://github.com/SpongePowered/SpongeForge/issues/503)

Now, we use [Mixin Technology](https://github.com/SpongePowered/Mixin/wiki) in order to transform classes, and we use this to add the interface `BlockType` (from SpongeAPI) to the existing `Block` class (see [`MixinBlock`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/block/MixinBlock.java#L70)). However, this does not seem to be happening when the TI transformer is loaded.
The issue is caused by your [`BlockTransformer`](https://github.com/TheDrunkMafia/ThaumicInfusion/blob/master/src/main/java/drunkmafia/thaumicinfusion/common/asm/BlockTransformer.java).
Ultimately, somehow our interface is not being added.

_Note that I don't know much about class transformation._

I think the problem is that you load classes from the LaunchClassLoader, but don't run transformers on them, so we never get to add our interface.
By applying the following patch, I fixed the issue
```diff
@@ -352,6 +352,9 @@ public class BlockTransformer implements IClassTransformer {
 
         try {
             byte[] bytecode = Launch.classLoader.getClassBytes(superName.replace('/', '.'));
+            for (IClassTransformer transformer : Launch.classLoader.getTransformers()) {
+                bytecode = transformer.transform(superName, superName, bytecode);
+            }
             if (bytecode == null) {
                 if (isObf)
                     bytecode = Launch.classLoader.getClassBytes(FMLDeobfuscatingRemapper.INSTANCE.unmap(superName.replace('.', '/')).replace('/', '.'));
```
However I don't know for sure that this is correct. I'm sure @Mumfrey would tell me whether this is right or not.

For reference, here's the TI_Transformer.log http://pastebin.com/6YcxbLq2

**Comment by Mumfrey** [comment]
Force-loading the superclass like this is a bad idea anyway, it's likely to break more things than just us. Putting a band-aid on it probably isn't the best solution, it would be better to just fix the transformer.

**Comment by Mumfrey** [comment]
Actually looking at what this is trying to do, actually just using Mixin might be a better choice.

**Comment by TheDrunkMafia** [comment]
I've looked into the issue and fixed the crashing, however am now running into an issue where it appears that sponge forge is removing an interface that TI injects into the world class.

**Comment by Mumfrey** [comment]
Mixin is actually only capable of *adding* interfaces, so if the changes aren't being observed in the output then either:

 * something is causing your transformers to not make it all the way to the end of the transformer chain
 * the presence of Mixin is screwing up your transformer chain.

One thing that might help is reading [this document explaining how mixins are applied](https://github.com/SpongePowered/Mixin/wiki/Introduction-to-Mixins---The-Mixin-Environment#how-mixins-do-their-thing) and also my reply to player in [this issue (linked paragraph)](https://github.com/SpongePowered/Mixin/issues/24#mixinloading) which explains the mixin application process.

Basically what Mixin does is first inspect the target class, it does this by loading it separately (not via the classloader), applying transformers, and then storing the information for later use.

When the class is **actually** transformed, the transformer then has all the information it needs to be able to transform the target class. These transformations happen *within* the transformer chain as per normal. The actions that Mixin can apply are limited to:

* Adding methods to the class
* *Replacing* existing methods in the class (never removing)
* Adding fields to the class
* Adding interfaces to the class
* Adding a call to a mixed-in method into an existing method (known as injecting) (incidentally this is the feature I think you could leverage to good effect)

The transformer simply doesn't have the capability to remove any part of a target class, it cannot remove interfaces or delete any member.

Be aware that when Mixin is present your transformer will run **twice** for **some** classes (any classes which are affected by mixin), the first time it will run is when generating the information required in the first pass I mentioned above, and the second time will be "for real" when the transformer runs in the transformer chain. This is what quite often confuses transformer authors if their transformer is designed to be "one shot" and therefore doesn't run on the second (real) pass.

If you think this might be the case, there are two options:

* You can decorate your transformer with an `@javax.annotation.Resource` annotation to prevent Mixin from applying your transformer in the first pass (this is not recommended if your transformer makes changes to the class which Mixin needs to be aware of, but is perfectly safe if you're not mutating the class too much)
* You can ensure that your transformer is not "stateful" and change its behaviour so that it can run multiple times for the same class.

As I said, that only applies if your transformer cares about being run multiple times on the same class.

If you want to talk about it in more detail then I'm on IRC most evenings from 11pm GMT, on `#spongedev` on Espernet. I would definitely suggest skim reading the Mixin documentation to see if it can replace your transformer, as it looks like it might be a good solution for you.

If you have any other questions feel free to ping me here, or open an issue in [SpongePowered/Mixin](https://github.com/SpongePowered/Mixin/issues).

**Comment by TheDrunkMafia** [comment]
Thank you for the help, it seems like everything is working now. I had to grab a modified version of a class writer that avoids loading of classes, I did notice that you do something similar since as you said you run transformers the first time and as it would seem, the class writer I was using before the change was the culprit of the crash that was reported.

**Comment by Mumfrey** [comment]
Yes Mixin [does precisely that](https://github.com/SpongePowered/Mixin/blob/initphase/src/main/java/org/spongepowered/asm/mixin/transformer/MixinClassWriter.java#L51-L74) (I use the metadata which is gathered in the first pass instead of triggering a re-entrant classloading behaviour). This is desirable to preserve the general classloading contract as much as possible, since allowing transformers to be re-entrant in that respect has some unpleasant repercussions.

Glad you were able to solve the problem, if you'd like to talk about Mixins any further then just poke me in IRC (I'm _**m**umfrey_ when offline and _**M**umfrey_ when online) at some point.

**Comment by TheDrunkMafia** [comment]
Will do. Again thanks for the help with resolving this crash.

**Comment by simon816** [comment]
I can confirm the issue has been fixed. Thanks!
