### ISSUE TITLE
A question and a crash with the new Gelum effect 

### ISSUE THREAD

**Issue by GWYOG** [TheDrunkMafia/ThaumicInfusion#69]
1. If lava is infused with this aspect, the cobblestone will  go back to lava when I leave this block. However, if water is infused with this aspect, the water block will become ice and never come back to water after I first go on it. Is this a feature or a bug?

2.  Encountering a crash when testing this infusion.
Using the purifying fluid from thaumcraft. I infused two blocks with Gelum and removed them. Then I placed a purifying fluid in one of them(only one). The other block was removed so that purifying fluid could flow into this block. Then when I walked onto the source block and then walked towards the flowing block, MC crashes.
These steps can be seen in these images: http://imgur.com/a/5EzAC
The crashreport is here: http://pastebin.com/ehnktMQx
Using TC-5.1.6 and TI-4.8

**Comment by TheDrunkMafia** [comment]
hmmm, sorry for being late in getting around to this, however been taking a break from MC modding to study. The first issue has been resolved, this was just a ticking issue were water wasn't letting the block tick whereas lava was, which has now been resolved in recent versions.

For the second issue, it seem's like this might be a bit more complicated to fix. I can only ask if this crash is still present in the recent update, if it is then I will investigate it. I hope I am wrong on my hunch about what is causing this issue, otherwise it will be one hell of a headache.

**Comment by GWYOG** [comment]
I fully understand that how heavy the schoolwork is, since I haven't played MC for several weeks and being absorbed in studying as well :P

Back to the topic, I tested this two issue just now, and found that both of them have been fixed in TI-4.82, the latest version of TI. 
So there's no need to worry about it now :)
