### ISSUE TITLE
Issue with Agricraft

### ISSUE THREAD

**Issue by Daxx367** [TheDrunkMafia/ThaumicInfusion#74]
First sorry if you all ready know about this but I checked and it doesn't seem its reported.

Game crashes on start-up, originally looked like an Agricraft issue but they believe it to be on your side.

My crash:
http://pastebin.com/MztLDkba
Agricraft issue post:
https://github.com/InfinityRaider/AgriCraft/issues/592

**Comment by TheDrunkMafia** [comment]
Yes, this would seem to be an issue with the transformer. I am going to need the TI_Transformer.log which is located in the root of your minecraft instance, to be able to debug the issue.

**Comment by TheDrunkMafia** [comment]
All test's I have conducted in my development environment as well as in various obfuscated environments, I have been unable to replicate this crash that you are running into. What other mods do you have installed?

**Comment by Tsukiumy** [comment]
i just see the link to here in the agricraft github, and for the mods, as far i can see are the people using the ftb unstable 1.8.9, as it has your mod in it
as for the log file, as its too big for the pastebin i uploaded it to the dropbox
https://dl.dropboxusercontent.com/u/36085879/TI_Transformer.log

**Comment by TheDrunkMafia** [comment]
Thats intresting then, I just used the Unstable pack to conduct the test and it loaded up fine, have you added or updated any of the mods?

**Comment by Daxx367** [comment]
All mods are uptodate and biomes aplenty is disabled, and Agricraft has been added. I will grab that file for you as soon as possible.

**Comment by ElvenChaos** [comment]
I'm getting the error too, so I'm submitting my crash log and TI_Trans log here.
I am using my own throw-together modpack for this.

Crash Log: http://pastebin.com/mTchQAj0
TI_Trans Log: https://www.dropbox.com/s/60guozqvbhnrvxq/TI_Transformer.log?dl=0

**Comment by TheDrunkMafia** [comment]
This is going to be a tricky crash to solve, as it seems to be only occurring when a certain other mod is present, it would of been nice for the unstable pack to have change logs, but they don't because it's "unstable".

TI is not directly causing this crash, since the method which in that class which has type cast crash, is not being touched by TI's transformer. I'd say it is being invoked as TI does still survey the class and will of injected bytecode into the other methods in that class. I'll have to look into which mods have changed from when it was working in the pack to when the crash occurs when agricraft is present.

**Comment by ElvenChaos** [comment]
If it helps I am not using the unstable pack, but the available to download versions of mods from curseforge.
Also, I tried removing ThInf from my pack, keeping AgrCraft, and the pack loaded up.

**Comment by TheDrunkMafia** [comment]
ThInf?

**Comment by ElvenChaos** [comment]
Thaumic Infusion, super short-handed.

**Comment by InfinityRaider** [comment]
What exactly are you dong with ASM? Are you adding methods to the Item or Block class? Because I'm suspecting it might just be that you've added a method with an identical signature (except with a different return type) as I'm adding to a subclass.

**Comment by TheDrunkMafia** [comment]
No, my transformer does not add any methods. It find's block method's with a world object and a block position, then add's in a hook for TI to switch between normal block functionality and infusion functionality. The method that is involved in this crash is never touched, this is why I am confused another mod is doing something to that method but when TI miniplates the bytecode of that class it invokes the crash caused by the changes made to that method.

**Comment by Daxx367** [comment]
Link to my TI_Transformer.log:
https://drive.google.com/file/d/0BzI--QMde-WZaWt4cjNRQ1FoOUE/view?usp=sharing 
And a list of all installed mods and versions:
http://pastebin.com/MLJ2i0MF
Sorry for all the other guff but I'm lazy.

**Comment by InfinityRaider** [comment]
Maybe its not just ThaumicInfusion and AgriCraft then...
@Daxx367 remove all coremods (except TI) and seeif it crashes:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.85.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  dsurroundcore (DynamicSurroundings-1.8.9-2.0.5.5.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)

**Comment by TheDrunkMafia** [comment]
I have resolved the issue, TI now works with agricraft. I have placed extra checks in my transformer to check for methods to blacklist. I'll release the new version on curse.
