### ISSUE TITLE
Random block ticks crashing server

### ISSUE THREAD

**Issue by bloodmc** [TheDrunkMafia/ThaumicInfusion#75]
Our server has been experiencing crashes due to random block ticks.

http://pastebin.com/bgThcbvN

The sponge line 

org.spongepowered.common.event.CauseTracker.randomTickBlock(CauseTracker.java:1075)

is simply calling 'block.randomTick' since we wrap the method for tracking reasons.  Can you add a safety check for the array being used in your BlockData class?

https://github.com/TheDrunkMafia/ThaumicInfusion/blob/master/src/main/java/drunkmafia/thaumicinfusion/common/world/data/BlockData.java#L194

Thanks!

**Comment by TheDrunkMafia** [comment]
This is an interesting crash, the fact it is happening means something is seriously going wrong during the initialization of Minecraft... This crash is pretty important, because with TI when Minecraft initializes. It index's each method within block classes and assigns them a unique id, this is then used latter down the line to figure out what method is being invoked.

The fact that a negative number is being passed in, in extremely disconcerting. The safety check will resolve the crash, but it won't fix the problem.

**Comment by TheDrunkMafia** [comment]
Nevermind, please try this version: http://puu.sh/o1sN4/9b4d199633.jar

The issue was a version controlling error, one of the lines in the transformer was reverted, so the wrong type of number was being passed into every method. This is a massive oversight on my part.

**Comment by bloodmc** [comment]
@TheDrunkMafia Thanks, testing the build now. I'll let you know how it turns out.

**Comment by bloodmc** [comment]
OK the server hasn't crashed for awhile. The build seemed to have fixed the issue. Thanks!
