### ISSUE TITLE
Incompatibility with DragonAPI v15a

### ISSUE THREAD

**Issue by kutschkem** [TheDrunkMafia/ThaumicInfusion#81]
DragonAPI v15a adds a FireSpread Event via ASM, apparently this clashes with one of your ASM  uses and produces a crash. See the closed issue over at Reika's issue tracker.

**Comment by TheDrunkMafia** [comment]
Please don't use the 1.7.10 version of the mod, it's an Alpha and served as a stress test to see if certain things were via-able. 1.7.10 is no longer supported, as I moved up to 1.8 and for fairly large reasons I can't update 1.7.10 since the ASM in 1.8 is fundamentally different since the method structure in 1.8 has changed.

**Comment by ReikaKalseki** [comment]
I am not asking you to update. I am asking for information. What ASM do you do to BlockFire?

**Comment by TheDrunkMafia** [comment]
Thaumic Infusion works by adding a event hook to all block methods, both overrides (those without super calls) and base methods of the block class. Hook makes it possible for Thaumic infusion to treat positions in the world is dynamic block's, this does not effect anything on vanilla side.

The 1.7.10 version was a stress test of both the storage system and ASM that was in place, for the ASM to work the transformer needs to be able to determine which methods are suitable for the system to work with. For this in 1.7, since the argument structure is World, X, Y, Z. This meant the transformer is effectively guessing which methods would work, so I abandoned 1.7. In favour of the BlockPos class for 1.8.

Since the crash is in 1.7.10 it can be any number of things within the transformer that caused it, since that was my first attempt at a dynamic transformer. From the looks of the crash, the detection of the world and coordinate parameters messed up. Which is why the VM is crashing at the type check.

**Comment by ReikaKalseki** [comment]
This may not be fixable...

**Comment by TheDrunkMafia** [comment]
It won't be, 1.7.10 was supposed to be a testing platform for the mod. 1.8.9 is the only stable and full release of the mod.

**Comment by ReikaKalseki** [comment]
So should I tell people not to use 1.7.10 TA?

**Comment by TheDrunkMafia** [comment]
Well, I've been telling people for ages that the 1.7.10 version is not to be used. But if you get an crash reports regarding TI and it's 1.7.10, just disregard it and tell them not to use it.
